title: Galantelab
author: Thiago L. A. Miller
email: tmiller@mochsl.org.br
timezone: America/Sao_Paulo
locale: pt-BR
lang: pt-BR
baseurl: "/blog"
url: "https://galantelab.github.io"
logo: assets/images/logo.png
favicon: assets/images/favicon.ico
paginate: 30
disqus: galantelab-blog
formspree: xeqbgnlg
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: ""
scholar:
  style: associacao-brasileira-de-normas-tecnicas
  sort_by: author
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - Dockerfile
  - docker-compose.yml

# Authors
authors:
  tmiller:
    name: Thiago Luiz Araujo Miller
    display_name: Thiago L. A. Miller
    citation_name: Miller, Thiago L. A.
    avatar: assets/images/tmiller.png
    description: >
      Formado em Engenharia Biotecnológica pela
      UNESP de Assis e Doutor em Ciências pelo
      Instituto de Química da USP. Atualmente
      trabalha como Pós-doutorando no laboratório
      Galantelab
  pgalante:
    name: Pedro Alexandre Favoretto Galante
    display_name: Pedro A. F. Galante
    citation_name: Galante, Pedro A. F.
    avatar: assets/images/pgalante.jpg
    description: >
      Sou um cientista! Minha formação acadêmica se
      iniciou com uma graduação em Ciâncias
      Moleculares (USP) e Doutorado em Bioquímica e
      Biologia Molecular (USP). Em seguinda, fiz um
      pós-doutorado na Universidade de Harvard (EUA).
      Atuei como Pesquisador Pleno no Ludwig Institute
      for Cancer Research e integrei a diretoria da
      Associação Brasileira de Bioinformática e
      Biologia Computacional. Atualmente, sou
      Pesquisador Sênior no Instituto Sírio-Libanês
      de Ensino e Pesquisa e coordeno - como adjunto -
      o Programa de Pós-graduação em Ciências da
      Saúde do Hospital Sírio-Libanês. Também sou
      um apaixonado por ciclismo (MTB e de estrada) e
      atividade física no geral. Meu dia a dia é
      liderar este grupo fantástico (Galante's lab) de
      cientista excepcionais nos nossos diversos
      projetos de pesquisa (como estes que apresentamos
      aqui)
  dmombach:
    name: Daniela Mombach
    display_name: Daniela Mombach
    citation_name: Mombach, Daniela
    avatar: assets/images/dmombach.jpg
    description: >
      Bióloga e doutoranda em genética e biologia
      molecular com foco no estudo de elementos
      transponíveis no câncer
  garantes:
    name: Gabriel Arantes dos Santos
    display_name: Gabriel A. dos Santos
    citation_name: dos Santos, Gabriel A.
    avatar: assets/images/garantes.png
    description: >
      Pós-doutorando no Galantelab estudando a
      expressão de retroelementos no câncer
  ndalessandre:
    name: Nathália D' Alessandre
    display_name: Nathália D' Alessandre
    citation_name: D' Alessandre, Nathália
    avatar: assets/images/ndalessandre.jpg
    description: >
      Bióloga e doutoranda no Galantelab,
      dedicando-se ao estudo de elementos
      transponíveis no câncer, com foco
      em HERV-K
  voliveira:
    name: Vitoria Regina Lima de Oliveira
    display_name: Vitoria R. L. de Oliveira
    citation_name: de Oliveira, Vitoria R. L.
    avatar: assets/images/voliveira.jpg
    description: >
      Graduanda de Engenharia Biotecnológica
      na UNESP de Assis e aluna de iniciação
      científica no Galantelab, dedicando-se
      ao estudo de reguladores da expressão
      gênica
  hconceicao:
    name: Helena Beatriz Conceição
    display_name: Helena B. Conceição
    citation_name: Conceição, Helena B.
    avatar: assets/images/hconceicao.jpg
    description: >
      Doutora em Bioinformática. Atualmente
      Pós-doutoranda no Galantelab, dedica-se
      ao estudo das retrocópias em humanos e
      outros organismos
  fferreira:
    name: Filipe Ferreira dos Santos
    display_name: Filipe F. dos Santos
    citation_name: dos Santos, Filipe F.
    avatar: assets/images/fferreira.jpg
    description: >
      Olá, apaixonados por ciência! Me formei em Ciências
      Biológicas (UNIFESP), seguido do Mestrado em
      Bioinformática (Ciências da Saúde) no Hospital
      Sírio-Libanês, orientado pelo Dr. Pedro A.F. Galante.
      Agora, sigo no Doutorado em Bioquímica e Biologia Molecular
      (USP). Tive a oportunidade de fazer uma graduação sanduíche
      em Bioinformática na University of Cincinnati (Ciência sem
      Fronteiras) e um intercâmbio de pesquisa na University of
      California San Diego (UCSD), ambas nos EUA. Amo estudar a
      genética molecular do câncer e de doenças infecciosas,
      usando dados OMICs, bioestatística e programação para
      desenvolver ferramentas e bancos de dados. Além do DNA e
      genes, também adoro jogar futebol, praticar esportes de
      areia e conviver com animais. Sejam bem-vindo(a)s!
  lcoliveira:
    name: Lorraine Christine de Oliveira
    display_name: Lorraine C. Oliveira
    citation_name: Oliveira, Lorraine C.
    avatar: assets/images/lcoliveira.jpg
    description: >
      Sou cientista apaixonada pelo que faço. Graduada em
      Ciências com habilitação em Biologia pela Universidade
      Federal de São Paulo (UNIFESP), atualmente sou mestranda
      em Bioinformática na Universidade de São Paulo (USP),
      onde desenvolvo minha pesquisa no laboratório do Dr.
      Pedro Galante. Investigo o fascinante universo das
      retrocópias e seus impactos evolutivos nas mais diversas
      espécies. Além disso, atuo como visiting scholar na Blue
      Marble Space, onde uno minha paixão por bioinformática e
      ciências espaciais, buscando compreender, por meio da
      biologia computacional, os mistérios que envolvem a vida
      no universo. ✨

# Social
social:
  twitter: https://twitter.com/GalanteLab
  github: https://github.com/galantelab

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-scholar
